apiVersion: helm.fluxcd.io/v2alpha1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 5m
  sourceRef:
    kind: HelmChart
    name: podinfo
  test:
    enable: true
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
