apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
commonLabels:
  env: production
resources:
  - ../../base/
  - namespace.yaml
patchesStrategicMerge:
  - version-patch.yaml
  - hpa-patch.yaml
